name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build Backend
      run: |
        cd Backend
        mvn clean install -DskipTests

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Build Frontend
      run: |
        cd ring-network-ui
        npm install
        npm run build

    - name: Run Backend Tests
      run: |
        cd Backend
        mvn test

    - name: Run Frontend Tests
      run: |
        cd ring-network-ui
        npm test -- --watchAll=false 